# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notification.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotificationDialog(object):
    def setupUi(self, NotificationDialog):
        NotificationDialog.setObjectName("NotificationDialog")
        NotificationDialog.resize(419, 68)
        NotificationDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(NotificationDialog)
        self.buttonBox.setGeometry(QtCore.QRect(330, 0, 71, 61))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(NotificationDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.label.setObjectName("label")

        self.retranslateUi(NotificationDialog)
        self.buttonBox.accepted.connect(NotificationDialog.accept)
        self.buttonBox.rejected.connect(NotificationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NotificationDialog)

    def retranslateUi(self, NotificationDialog):
        _translate = QtCore.QCoreApplication.translate
        NotificationDialog.setWindowTitle(_translate("NotificationDialog", "Period end"))
        self.label.setText(_translate("NotificationDialog", "Period ended"))
